spring:
  application:
    name: api-gateway
server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

 #Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

zuul:
 routes:
   hello-world:
     path: /hello-world/**
     url: http://localhost:8081




#si on s'enregistre avec eureka on ne doit plus
#declarer chaque microservce comme dand l'exemple au dessus


