spring:
  application:
    name: zuul
server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


#zuul:
#  prefix: /api
#  routes:
#    db:
#      path: /db/**
#      url: http://localhost:8081


#si on s'enregistre avec eureka on ne doit plus
#declarer chaque microservce comme dand l'exemple au dessus


